import type { AgentStatus, HistoryPoint } from './types';

export const initialAgents: AgentStatus[] = [
  {
    id: 'ag-101',
    lastSeen: new Date(),
    status: 'online',
    schedulerMode: 'auto',
    selectedLink: 'satcom',
    messagesInQueue: 2,
    nextDeliveryTime: new Date(Date.now() + 5000),
    serverLut: new Date(),
    linkType: 'satcom',
    linkAvailable: true,
    linkQuality: 0.98,
    latency: 72,
    reliability: 0.98,
    linkTimestamp: new Date(),
    unit: 'פיקוד צפון',
    unit_code: 'N-001',
    zayad_id: 'Z-101',
    call_sign: 'N-ALPHA',
    platformId: 'plat-101',
    platformName: 'Platform Alpha',
  },
  {
    id: 'ag-204',
    lastSeen: new Date(),
    status: 'warning',
    schedulerMode: 'manual',
    selectedLink: 'lte',
    messagesInQueue: 14,
    nextDeliveryTime: new Date(Date.now() + 10000),
    serverLut: new Date(),
    linkType: 'lte',
    linkAvailable: true,
    linkQuality: 0.86,
    latency: 181,
    reliability: 0.86,
    linkTimestamp: new Date(),
    unit: 'ממסר מזרח',
    unit_code: 'E-002',
    zayad_id: 'Z-204',
    call_sign: 'E-ROOK',
    platformId: 'plat-204',
    platformName: 'Platform Beta',
  },
  {
    id: 'ag-309',
    lastSeen: new Date(),
    status: 'online',
    schedulerMode: 'auto',
    selectedLink: 'rf',
    messagesInQueue: 6,
    nextDeliveryTime: new Date(Date.now() + 8000),
    serverLut: new Date(),
    linkType: 'rf',
    linkAvailable: true,
    linkQuality: 0.92,
    latency: 104,
    reliability: 0.92,
    linkTimestamp: new Date(),
    unit: 'מבצעי ים',
    unit_code: 'SEA-003',
    zayad_id: 'Z-309',
    call_sign: 'SEA-77',
    platformId: 'plat-309',
    platformName: 'Platform Gamma',
  },
  {
    id: 'ag-412',
    lastSeen: new Date(),
    status: 'offline',
    schedulerMode: 'auto',
    selectedLink: 'satcom',
    messagesInQueue: 27,
    nextDeliveryTime: new Date(Date.now() + 20000),
    serverLut: new Date(),
    linkType: 'satcom',
    linkAvailable: false,
    linkQuality: 0.51,
    latency: 350,
    reliability: 0.51,
    linkTimestamp: new Date(),
    unit: 'צומת מערב',
    unit_code: 'W-004',
    zayad_id: 'Z-412',
    call_sign: 'W-HALO',
    platformId: 'plat-412',
    platformName: 'Platform Delta',
  },
];

export const history: HistoryPoint[] = [
  { time: '10:00', latency: 75, reliability: 0.99 },
  { time: '10:15', latency: 88, reliability: 0.97 },
  { time: '10:30', latency: 95, reliability: 0.95 },
  { time: '10:45', latency: 121, reliability: 0.93 },
  { time: '11:00', latency: 110, reliability: 0.94 },
  { time: '11:15', latency: 84, reliability: 0.97 },
];
